Add placeholder images, fix standalone comicarchive
* Standalone comicarchive now runs properly and installs
* A none-image asset is added to a libs folder on install
* When a page's extension is undetected, none-image is used instead
* Remove versioning artifact files from bbuild 4.x
* Clean up directory when no pages downloaded

diff --git a/bin/comicarchive b/bin/comicarchive
--- a/bin/comicarchive
+++ b/bin/comicarchive
@@ -2,11 +2,14 @@
 
 ### comicarchive Usage:help
 #
+#	comicarchive { cbz | pdf } COMICFOLDER
+#	make_archive:main { cbz | pdf } COMICFOLDER
+#
 # When run as standalone, the comicarchive command/subroutine turns a folder of
 #
 # 	chapter_X/page_*
 #
-# into a single chapter_X.pdf or chpater_X.cbz
+# into a single chapter_X.pdf or chapter_X.cbz
 #
 # Set NOREMOVE=true to prevent removeal of original files
 #
@@ -96,17 +99,23 @@ bincheck:path() {
 #
 # Example:
 # 	
-# 	echo "${CRED}Some red text ${CBBLU} some blue text $CDEF some text in the terminal's default colour"
+# 	echo -e "${CRED}Some red text ${CBBLU} some blue text $CDEF some text in the terminal's default colour"
+#
+# Requires processing of escape characters.
 #
 # Colours available:
 #
-# CDEF -- switches to the terminal default
+# CRED, CBRED, HLRED -- red, bold red, highlight red
+# CGRN, CBGRN, HLGRN -- green, bold green, highlight green
+# CYEL, CBYEL, HLYEL -- yellow, bold yellow, highlight yellow
+# CBLU, CBBLU, HLBLU -- blue, bold blue, highlight blue
+# CPUR, CBPUR, HLPUR -- purple, bold purple, highlight purple
+# CTEA, CBTEA, HLTEA -- teal, bold teal, highlight teal
 #
-# CRED, CBRED -- red, bold red
-# CGRN, CBGRN -- green, bold green
-# CYEL, CBYEL -- yellow, bold yellow
-# CBLU, CBBLU -- blue, bold blue
-# CPUR, CBPUR -- purple, bold purple
+# CDEF -- switches to the terminal default
+# CUNL -- add underline
+#
+# Note that highlight and underline must be applied or re-applied after specifying a colour.
 #
 ###/doc
 
@@ -115,31 +124,53 @@ export CGRN="\033[0;32m"
 export CYEL="\033[0;33m"
 export CBLU="\033[0;34m"
 export CPUR="\033[0;35m"
+export CTEA="\033[0;36m"
+
 export CBRED="\033[1;31m"
 export CBGRN="\033[1;32m"
 export CBYEL="\033[1;33m"
 export CBBLU="\033[1;34m"
 export CBPUR="\033[1;35m"
+export CBTEA="\033[1;36m"
+
+export HLRED="\033[41m"
+export HLGRN="\033[42m"
+export HLYEL="\033[43m"
+export HLBLU="\033[44m"
+export HLPUR="\033[45m"
+export HLTEA="\033[46m"
+
 export CDEF="\033[0m"
+
+### Console output handlers Usage:bbuild
+#
+# Write data to console stderr using colouring
+#
+###/doc
 
 ### Environment Variables Usage:bbuild
 #
-# MODE_DEBUG : set to 'yes' to enable debugging output
-# MODE_DEBUG_VERBOSE : set to 'yes' to enable command echoing
+# MODE_DEBUG : set to 'true' to enable debugging output
+# MODE_DEBUG_VERBOSE : set to 'true' to enable command echoing
 #
 ###/doc
 
+: ${MODE_DEBUG=false}
+: ${MODE_DEBUG_VERBOSE=false}
 
-MODE_DEBUG=no
-MODE_DEBUG_VERBOSE=no
+# Internal
+function out:buffer_initialize {
+	OUTPUT_BUFFER_defer=(:)
+}
+out:buffer_initialize
 
 ### out:debug MESSAGE Usage:bbuild
 # print a blue debug message to stderr
-# only prints if MODE_DEBUG is set to "yes"
+# only prints if MODE_DEBUG is set to "true"
 ###/doc
 function out:debug {
-	if [[ "$MODE_DEBUG" = yes ]]; then
-		echo -e "${CBBLU}DEBUG:$CBLU$*$CDEF" 1>&2
+	if [[ "$MODE_DEBUG" = true ]]; then
+		echo -e "${CBBLU}DEBUG: $CBLU$*$CDEF" 1>&2
 	fi
 }
 
@@ -154,7 +185,41 @@ function out:info {
 # print a yellow warning message to stderr
 ###/doc
 function out:warn {
-	echo -e "${CBYEL}WARN:$CYEL $*$CDEF" 1>&2
+	echo -e "${CBYEL}WARN: $CYEL$*$CDEF" 1>&2
+}
+
+### out:defer MESSAGE Usage:bbuild
+# Store a message in the output buffer for later use
+###/doc
+function out:defer {
+	OUTPUT_BUFFER_defer[${#OUTPUT_BUFFER_defer[@]}]="$*"
+}
+
+### out:flush HANDLER ... Usage:bbuild
+#
+# Pass the output buffer to the command defined by HANDLER
+# and empty the buffer
+#
+# Examples:
+#
+# 	out:flush echo -e
+#
+# 	out:flush out:warn
+#
+# (escaped newlines are added in the buffer, so `-e` option is
+#  needed to process the escape sequences)
+#
+###/doc
+function out:flush {
+	[[ -n "$*" ]] || out:fail "Did not provide a command for buffered output\n\n${OUTPUT_BUFFER_defer[*]}"
+
+	[[ "${#OUTPUT_BUFFER_defer[@]}" -gt 1 ]] || return
+
+	for buffer_line in "${OUTPUT_BUFFER_defer[@]:1}"; do
+		"$@" "$buffer_line"
+	done
+
+	out:buffer_initialize
 }
 
 ### out:fail [CODE] MESSAGE Usage:bbuild
@@ -170,9 +235,28 @@ function out:fail {
 		ERCODE="$1"; shift
 	fi
 
-	echo -e "${CBRED}ERROR FAIL:$CRED$*$CDEF" 1>&2
+	echo -e "${CBRED}ERROR FAIL: $CRED$*$CDEF" 1>&2
 	exit $ERCODE
 }
+
+### out:error MESSAGE Usage:bbuild
+# print a red error message to stderr
+#
+# unlike out:fail, does not cause script exit
+###/doc
+function out:error {
+	echo -e "${CBRED}ERROR: ${CRED}$*$CDEF" 1>&2
+}
+
+### out:dump Usage:bbuild
+#
+# Dump stdin contents to console stderr. Requires debug mode.
+#
+# Example
+#
+# 	action_command 2>&1 | out:dump
+#
+###/doc
 
 function out:dump {
 	echo -e -n "${CBPUR}$*" 1>&2
@@ -181,64 +265,108 @@ function out:dump {
 	echo -e -n "$CDEF" 1>&2
 }
 
+### out:break MESSAGE Usage:bbuild
+#
+# Add break points to a script
+#
+# Requires MODE_DEBUG set to true
+#
+# When the script runs, the message is printed with a propmt, and execution pauses.
+#
+# Press return to continue execution.
+#
+# Type `exit`, `quit` or `stop` to stop the program. If the breakpoint is in a subshell,
+#  execution from after the subshell will be resumed.
+#
+###/doc
+
 function out:break {
-	[[ "$MODE_DEBUG" = yes ]] || return
+	[[ "$MODE_DEBUG" = true ]] || return
 
 	read -p "${CRED}BREAKPOINT: $* >$CDEF " >&2
-	if [[ "$REPLY" =~ $(echo 'quit|exit|stop') ]]; then
+	if [[ "$REPLY" =~ quit|exit|stop ]]; then
 		out:fail "ABORT"
 	fi
 }
 
-[[ "$MODE_DEBUG_VERBOSE" = yes ]] && set -x || :
+if [[ "$MODE_DEBUG_VERBOSE" = true ]]; then
+	set -x
+fi
 #!/bin/bash
 
-### abspath Usage:bbuild
+### abspath:path RELATIVEPATH Usage:bbuild
 # Returns the absolute path of a file/directory
-#
-# Exposes two functions
-#
-#     abspath:path
-#     abspath:simple
-#
-# Do not use the python-based 'abspath:path' for intensitve resolution;
-# instead, use native 'abspath:simple' which is at least 170 times
-# more efficient, at the cost of perhaps being potentially
-# dumber (simply collapses '/./' and '/../').
-# 
-# Neither utility expands softlinks.
-#
-# If python is not found, abspath:path falls back to abspath:simple systematically.
 ###/doc
 
 function abspath:path {
-	local newvar=${1//"'"/"\\'"}
-	(
-		set +eu
-		if which python >/dev/null 2>&1; then
-			python  -c "import os ; print os.path.abspath('$newvar')"
-		elif which python3 >/dev/null 2>&1 ; then
-			python3 -c "import os ; print(os.path.abspath('$newvar') )"
-		else
-			abspath:simple "$newvar"
-		fi
-	)
-}
-
-# More efficient by a factor of at least 170:1
-# compared to spinning up a python process every time
-function abspath:simple {
 	local workpath="$1"
 	if [[ "${workpath:0:1}" != "/" ]]; then workpath="$PWD/$workpath"; fi
-	for x in {1..50}; do # set a limit on how many iterations - only very stupid paths will get us here.
-		if [[ "$workpath" =~ '/../' ]] || [[ "$workpath" =~ '/./' ]]; then
-			workpath="$(echo "$workpath"|sed -r -e 's#/./#/#g' -e 's#([^/]+)/../#\1/#g' -e 's#/.$##' -e 's#([^/]+)/..$#\1#' )"
-		else
+
+	workpath="$(abspath:strip_dot "$workpath")"
+	abspath:resolve_dotdot "$workpath" | sed -r 's|/$||'
+}
+
+function abspath:strip_dot {
+	echo "$1" | sed -r 's@/\./@/@g;s@/.$@@'
+}
+
+function abspath:resolve_dotdot {
+	local workpath="$1"; shift
+
+	# Set a limit on how many iterations to perform
+	# Only very obnoxious paths should fail
+	for x in {1..50}; do
+		#out:info "Iteration $x : $workpath"
+
+		# No more dot-dots - good to go
+		if [[ ! "$workpath" =~ /\.\.(/|$) ]]; then
 			echo "$workpath"
 			return 0
 		fi
+
+		# Starts with an up-one at root - unresolvable
+		if [[ "$workpath" =~ ^/\.\.(/|$) ]]; then
+			return 1
+		fi
+
+		workpath="$(echo "$workpath"|sed -r 's@[^/]+/\.\.(/|$)@@;s@/$@@')"
 	done
-	return 1 # hopefully we never get here
+
+	# A very obnoxious path was used.
+	return 1
+}
+### runmain SCRIPTNAME FUNCTION [ARGUMENTS ...] Usage:bbuild
+#
+# Runs the function FUNCTION with ARGUMENTS, only if the runtime
+# name of the script matches SCRIPTNAME
+#
+# This allows you include a main-like function in your library
+# that only runs if you use your lib as an executabl itself.
+#
+# For example, an image archiver could be:
+#
+# 	function archive_images {
+# 		tar czf "$1.tgz" "$@"
+# 	}
+#
+# 	runmain archiveimages.sh archive_images "$@"
+#
+# When included a different script, the runmain call does not fire the lib's function
+#
+# If the lib is compiled/made executable, and named "archiveimages.sh", the function runs.
+#
+# This is similar to `if __name__ == "__main__"` clauses in python
+#
+###/doc
+
+function runmain {
+	local required_name="$1"; shift
+	local funcall="$1"; shift
+	local scriptname="$(basename "$0")"
+
+	if [[ "$required_name" = "$scriptname" ]]; then
+		"$funcall" "$@"
+	fi
 }
 
 make_archive:remove() {
@@ -247,7 +375,7 @@ make_archive:remove() {
 }
 
 make_archive:pdf() {
-	local targetdir="$(abspath:simple "$1")"; shift
+	local targetdir="$(abspath:path "$1")"; shift
 	local archivename="$targetdir.pdf"
 
 	if bincheck:has img2pdf; then
@@ -264,7 +392,7 @@ make_archive:pdf() {
 }
 
 make_archive:cbz() {
-	local targetdir="$(abspath:simple "$1")"; shift
+	local targetdir="$(abspath:path "$1")"; shift
 	local archivename="$targetdir.cbz"
 
 	if bincheck:has zip; then
@@ -274,7 +402,7 @@ make_archive:cbz() {
 		#  since they're literally a ZIP file
 		#  and displayed in name order
 		cd "$targetdir/"
-		zip "$archivename" page_* && {
+		zip "$archivename" $(echo page_*) && {
 			cd ..
 			make_archive:remove "$targetdir"
 		}
diff --git a/src/mfcom b/src/mfcom
--- a/src/mfcom
+++ b/src/mfcom
@@ -44,6 +44,7 @@ LASTINDEXFILE="last-tried.txt"
 #%include runmain.sh
 #%include out.sh autohelp.sh varify.sh
 #%include comicarchive
+#%include searchpaths.sh
 
 wgetdl() {
 	local downloadfile="$1"; shift
@@ -97,7 +98,8 @@ do_unzip() {
 
 set_image_extension() {
 	local imagefile="$1"; shift
-	local imagetype="$(file "$imagefile"|egrep -oi 'jpeg|jpg|png|gif' | tr '[:upper:]' '[:lower:]')"
+	local typestring="$(file "$imagefile")"
+	local imagetype="$(echo "$typestring"|egrep -oi 'jpeg|jpg|png|gif' | tr '[:upper:]' '[:lower:]')"
 	local extension=bin
 
 	out:debug "Renaming $imagefile"
@@ -108,7 +110,10 @@ set_image_extension() {
 		png|gif)
 			extension="$imagetype" ;;
 		*)
-			out:warn "Could not determine extension for $imagefile"
+			out:warn "Could not determine extension for [$imagefile] : $typestring)"
+			out:debug "    (using $noimgf instead)"
+			rm "$imagefile" 2>/dev/null || :
+			cp "$noimgf" "${imagefile}.png"
 			return ;;
 	esac
 
@@ -171,6 +176,7 @@ download_chapter() {
 
 	[[ "$i" -gt 0 ]] || {
 		out:warn "Nothing downloaded !"
+		rm -r "$targetdir"
 		return
 	}
 
@@ -276,6 +282,14 @@ announce_setup() {
 	sleep 2
 }
 
+get_noimg() {
+	local nilplaces
+	nilplaces="$HOME/.local/lib/mfcom:/usr/local/lib/mfcom"
+	noimgf="$(searchpaths:file_from "$nilplaces" none.png)"
+
+	[[ -n "$noimgf" ]] || out:fail "Could not find nil image none.png amongst [$nilplaces]"
+}
+
 main() {
 	if [[ -z "$*" ]]; then
 		autohelp:print
@@ -285,6 +299,8 @@ main() {
 	: ${MFCOM_UAGENT="Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0"}
 
 	: ${MFCOM_WAIT=2}
+
+	get_noimg
 
 	get_main_url "$1"; shift
 	setup_configuration "${1:-}" "${2:-}"
