make URL reloadable from folder status

diff --git a/src/mfcom b/src/mfcom
--- a/src/mfcom
+++ b/src/mfcom
@@ -38,6 +38,9 @@
 
 set -euo pipefail
 
+SURLFILE="source.url"
+LASTINDEXFILE="last-tried.txt"
+
 #%include version.sh notest.sh
 #%include bashout.sh autohelp.sh varify.sh getbin.sh
 #%include comicarchive
@@ -142,10 +145,17 @@ function download_chapter {
 	local chapter_url="$1"; shift
 	local base_url="$(dirname "$chapter_url")"
 	local targetdir="$1"; shift
+	local chapnum="$1"; shift
+
+	targetdir="$targetdir/chapter_${chapnum}"
+
 	local dlfile="$targetdir/fpage.html"
 	local chapdir="$(basename "$targetdir")"
 
 	mkdir -p "$targetdir"
+
+	# Register the last attempt now, in case fail before end
+	echo "$chapnum" > "$F_LASTDONE"
 
 	wgetdl "$dlfile" "$chapter_url"
 
@@ -157,6 +167,10 @@ function download_chapter {
 		download_chapter_page "$base_url/$i.html" "$targetdir/page_$(padnum "$i")"
 		sleep "$MFCOM_WAIT"
 	done
+
+	# FIXME this will not work with non-int chapters ... !
+	local cn="$(unzero "$chapnum")"
+	echo "$((cn+1))" > "$F_LASTDONE"
 
 	local archivename="$(varify_fil "$chapdir")"
 	if [[ "${MFCOM_MAKE_ARCHIVE:-}" = pdf ]]; then
@@ -185,7 +199,7 @@ function download_all_chapters {
 			fi
 		fi
 		
-		download_chapter "$LINKLINE" "$D_TARGET/chapter_${i}"
+		download_chapter "$LINKLINE" "$D_TARGET" "${i}"
 
 	done < "$F_LINKS"
 }
@@ -194,21 +208,21 @@ function numcheck {
 	local tocheck="$1"; shift
 
 	if [[ ! "$tocheck" =~ ^[0-9]*$ ]]; then
-		faile Invalid "$*"
+		faile "Invalid number: $*"
 	fi
 }
 
-function main {
-	if [[ -z "$*" ]]; then
-		printhelp
-		exit
-	fi
-
-	: ${MFCOM_UAGENT="Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0"}
-
-	: ${MFCOM_WAIT=2}
-
+function get_main_url {
 	U_MAINPAGE="$1"; shift
+
+	if [[ -d "$U_MAINPAGE" ]]; then
+		U_MAINPAGE="$(cat "$U_MAINPAGE/$SURLFILE")"
+	elif [[ ! "$U_MAINPAGE" =~ ^https?:// ]]; then
+		faile "Invalid page URL $U_MAINPAGE"
+	fi
+}
+
+function setup_configuration {
 	# Mangafox has started generating urls without schemes
 	U_MAINPAGE_NOSCHEME="$(echo "$U_MAINPAGE"|sed -r 's|https?://|//|')"
 
@@ -222,14 +236,36 @@ function main {
 	D_TARGET="${D_TARGET%_}"
 	F_MAIN="$D_TARGET/frontpage.html"
 	F_LINKS="$D_TARGET/links.txt"
+	F_SOURCEURL="$D_TARGET/$SURLFILE"
+	F_LASTDONE="$D_TARGET/$LASTINDEXFILE"
+
+	mkdir -p "$D_TARGET"
+
+	[[ -f "$F_SOURCEURL" ]] || echo "$U_MAINPAGE" > "$F_SOURCEURL"
+	[[ -z "$STARTINDEX" ]] && [[ -f "$F_LASTDONE" ]] && STARTINDEX="$(cat "$F_LASTDONE")" || :
+}
+
+function main {
+	if [[ -z "$*" ]]; then
+		printhelp
+		exit
+	fi
+
+	: ${MFCOM_UAGENT="Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0"}
+
+	: ${MFCOM_WAIT=2}
+
+	get_main_url "$1"; shift
+	setup_configuration "${1:-}" "${2:-}"
+	shift 2 || :
 
 	# =====================
 	echo "MFCOM_WAIT=$MFCOM_WAIT"
 	echo "MFCOM_MAKE_ARCHIVE=${MFCOM_MAKE_ARCHIVE:-}"
 	echo "Downloading to: $D_TARGET"
+	echo "Starting at: $STARTINDEX"
+	echo "Ending at: $ENDINDEX"
 	sleep 2
-
-	mkdir -p "$D_TARGET"
 
 	get_mainList
 	extract_links "$F_MAIN" "$F_LINKS"
